Update README.md with additional resources and articles
graphrag/awesome-graphrag pull request #2
Opened 2024-11-26 10:55 UTC by lundqdec

Hi,

I've added a great article from towarddatascience where the author implements the [GraphReader paper](https://arxiv.org/abs/2406.14550) with Neo4j and LangGraph.

I also added two more GraphRag implementations:
1. nano-graphrag, which recreated Microsofts GraphRAG with just 1100 lines of code (except tests and prompts)
2. fast-graphrag, which used nano-graphrag, implemented it further and built a proprietary managed service around it

🙂

2024-11-27 12:30 UTC, akollegger requested changes
Thank you @lundqdec these are great additions. I've made some minor comments about section names and sorting. WDYT?

2024-11-27 12:30 UTC, akollegger commented on readme.md
>  ### Notable Blog Posts
Shall we collapse the "Articles" and "Notable Blog Posts" sections into simply "Articles"?

2024-11-27 12:30 UTC, akollegger commented on readme.md
> +- [gusye1234/nano-graphrag](https://github.com/gusye1234/nano-graphrag)
Let's try keep this list alphabetized, as the most neutral sorting.

2024-11-27 15:23 UTC, lundqdec commented on readme.md
>  ### Notable Blog Posts
Hi, sounds like a good idea!

2024-11-28 09:55 UTC, akollegger approved these changes
Awesome, thank you!

2024-11-28 09:55 UTC, merged